package com.mycompany.uniburguerretaguarda.gui.produto;

import com.mycompany.uniburguerretaguarda.model.Categoria;
import com.mycompany.uniburguerretaguarda.model.Produto;
import com.mycompany.uniburguerretaguarda.service.CategoriaService;
import com.mycompany.uniburguerretaguarda.service.ProdutosService;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProdutosConsultaGUI extends javax.swing.JFrame {
    
    private List<Produto> produtos = new ArrayList<>();
    private List<Categoria> categorias = new ArrayList<>();
    ProdutosService produtosService = new ProdutosService();
    CategoriaService categoriaService = new CategoriaService();

    public ProdutosConsultaGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        carregarCboCategoria();
        consultar();
    }
    
    private void carregarCboCategoria() {
        categorias = categoriaService.getCategorias();
        
        DefaultComboBoxModel dml = new DefaultComboBoxModel();
        
        dml.addElement("TODOS");
        
        for (int i = 0; i < categorias.size(); i++) {
            dml.addElement(categorias.get(i).getDescricao());
        }
        
        cboCategoria.setSelectedItem("TODOS");
        cboCategoria.setModel(dml);
    }
    
    private void consultar() {
        produtos = produtosService.getProdutos();
        
        if (!cboCategoria.getSelectedItem().equals("TODOS")) {
            int idCategoria = categorias.stream().filter(i -> i.getDescricao().equals(cboCategoria.getSelectedItem())).findFirst().get().getId();
            produtos = produtos.stream().filter(i -> i.getTipo_produto() == idCategoria).collect(Collectors.toList());
        }

        popularTabela();
    }
    
    private void popularTabela() {
        if (produtos.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Lista de Produtos vazia!", "", JOptionPane.INFORMATION_MESSAGE);
        }
        
        Object info[][] = new Object[produtos.size()][5];
        
        int i = 0;
        for (Produto produto : produtos) {
            Optional<Categoria> categoria = categorias.stream().filter(cat -> cat.getId() == produto.getTipo_produto()).findFirst();
            
            if (categoria.isEmpty()) {
                continue;
            }
            
            info[i][Tabela.ID.getId()] = produto.getId();
            info[i][Tabela.NOME.getId()] = produto.getNome();
            info[i][Tabela.DESCRICAO.getId()] = produto.getDescricao();
            info[i][Tabela.CATEGORIA.getId()] = categoria.get().getDescricao();
            info[i][Tabela.PRECO.getId()] = produto.getPrecoFormatado();
            
            i++;
        }

        setModel(info);
    }
    
    private void setModel(Object info[][]) {
        String colunas[] = {
           "ID", "Nome", "Descrição", "Categoria", "Preço"
        };
        
        tblProduto.setModel(new DefaultTableModel(
                info,
                colunas
        ) {
            boolean[] canEdit = new boolean[]{
                false,false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        }
        );
    }
    
    private Produto getSelecionado() {
        return produtos.get(tblProduto.getSelectedRow());
    }
    
    private void incluir() {
        ProdutoCadastroGUI form = new ProdutoCadastroGUI();
        form.incluir(categorias);
        
        form.setVisible(true);
    }
    
    private void visualizar() throws IOException {
        ProdutoCadastroGUI form = new ProdutoCadastroGUI();
        form.setProduto(getSelecionado(), categorias);
        
        form.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        cboCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Excluir");

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        try {
            visualizar();
        } catch (IOException ex) {
            Logger.getLogger(ProdutosConsultaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                visualizar();
            } catch (IOException ex) {
                Logger.getLogger(ProdutosConsultaGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblProdutoMouseClicked

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        incluir();
    }//GEN-LAST:event_btnIncluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduto;
    // End of variables declaration//GEN-END:variables

    private enum Tabela {
        
        ID(0),
        NOME(1),
        DESCRICAO(2),
        CATEGORIA(3),
        PRECO(4);
        
        private final int id;
        
        Tabela(int id) {
            this.id = id;
        }
        
        public int getId() {
            return this.id;
        }
    }
}
